// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlqpI1pNxMLU8aPlYoYgEPXUHwvUJgTvE',
    appId: '1:969352970346:web:39e459222d94c5055e0a13',
    messagingSenderId: '969352970346',
    projectId: 'click-33a39',
    authDomain: 'click-33a39.firebaseapp.com',
    databaseURL: 'https://click-33a39-default-rtdb.firebaseio.com',
    storageBucket: 'click-33a39.appspot.com',
    measurementId: 'G-6RRKN6HRPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIc03CVhEm8xLCJgtIRKwQF_F-18nWzBg',
    appId: '1:969352970346:android:d5ad6b8d747c897e5e0a13',
    messagingSenderId: '969352970346',
    projectId: 'click-33a39',
    databaseURL: 'https://click-33a39-default-rtdb.firebaseio.com',
    storageBucket: 'click-33a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPS9WaTEhJqt9aOoQZEeaT0TbLFq0DsdY',
    appId: '1:969352970346:ios:8d09ce695af777bd5e0a13',
    messagingSenderId: '969352970346',
    projectId: 'click-33a39',
    databaseURL: 'https://click-33a39-default-rtdb.firebaseio.com',
    storageBucket: 'click-33a39.appspot.com',
    iosClientId: '969352970346-pnlgqgdth5rndd24bsj4qk8coi9noq0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.level1verison',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPS9WaTEhJqt9aOoQZEeaT0TbLFq0DsdY',
    appId: '1:969352970346:ios:582daacc949b39235e0a13',
    messagingSenderId: '969352970346',
    projectId: 'click-33a39',
    databaseURL: 'https://click-33a39-default-rtdb.firebaseio.com',
    storageBucket: 'click-33a39.appspot.com',
    iosClientId: '969352970346-vhj030aise2bb8th261a5kgu0lt5e2vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.level1verison.RunnerTests',
  );
}
